# Generated by Django 5.1.3 on 2024-11-20 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
