# Generated by Django 5.1.3 on 2024-11-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='value',
            new_name='balance',
        ),
    ]
